### PR TITLE
Putting back datepicker languages resources updated to JQuery 1.12.1.

### PR DESCRIPTION
**Pull request by florianlacreuse**
See issue #3.

Duplicate files/locales (see note on `DatePickerLanguages` inner class), need to be checked:
- Hebrew: "he" resource file copied to "iw".
- Indonesian: "id" resource file copied to "in".
- Kazakh: "kk" resource file copied to "kz".

New locales (see `DatePickerLanguages`), need to be checked:
- `BELARUSIAN("be")`
- `SWISS_ITALIAN("it", "CH")`

### CODE REVIEW

**Comment by martin-g** [comment]
@papegaaij Do you want to take a look ?

**Comment by papegaaij** [comment]
I agree, it was a mistake to remove these files. I removed them because they were no longer part of the distribution and I was under the intention that they were no longer needed, but they are.

**Comment by papegaaij** [comment]
I'm still checking the renamed locales. It seems we need to use the old names, not the new names.

**Comment by martin-g** [comment]
@papegaaij Let me know when you are ready and I will cut a release!

**Comment by papegaaij** [comment]
I've checked all locales and added quite a few new ones. I've also added a testcase for the 3 renamed locales: in -> id, iw -> he, ji -> yi. The locale 'kz' never existed and was wrong, the proper locale is 'kk'.

@martin-g you can cut a release now

**Comment by florianlacreuse** [comment]
@papegaaij Thank you for checking all locales. I tried to make it work for the PR without breaking stuffs, with previous code / enum on the one hand and the new jquery resources files on the other hand. Anyway, thanks again for this clean up.

**Comment by martin-g** [comment]
8.1 has been released and soon will be available at Maven Central!
Thank you @florianlacreuse and @papegaaij !

**Pull request merged**
