### PR TITLE
Upgraded jquery-ui from 1.12.1 to 1.13.0

### PR DESCRIPTION
**Pull request by akramshuja**

### CODE REVIEW

**Comment by brunoborges** [comment]
Instead of a PR that replaces the .js files, I think it would be better if you could provide a PR that contains a shell script that performs such update, or a detail on the checksums of the files being updated here, so miantainers can more safely review and trust the minified JS file.

**Comment by akramshuja** [comment]
@brunoborges Can I attach a txt of the checksums of the files updated in this comment thread?

**Comment by brunoborges** [comment]
Send the URL of where we can find the original files and where their checksums are hosted.

**Comment by akramshuja** [comment]
https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/

jquery-ui Themes package(contains the css and minified css as well as the new images for wiquery/ui/themes/smoothness):
https://jqueryui.com/resources/download/jquery-ui-themes-1.13.0.zip

The js and min js files were picked from:
https://jqueryui.com/resources/download/jquery-ui-1.13.0.zip

**Comment by martin-g** [comment]
Thank you, @akramshuja !
I will test the PR later today!

**Comment by martin-g** [comment]
Thanks for the contribution, @akramshuja !
I've merged it to `master` branch that I've just updated to Wicket 9.7.0 and changed its version to 9.0.0-SNAPSHOT.

If you need to update `wicket-8` (just created from master before the update to Wicket 9.x) then we may need to hear what the other maintainers of WiQuery think of. I don't use WiQuery in any application, so I am fine, but someone who uses it might be against such upgrade in a minor release.

**Comment by brunoborges** [comment]
@martin-g did you check the checksums?

**Comment by akramshuja** [comment]
@martin-g From what I understand, there will be a major release of wiquery-core and wiquery-jquery-ui libraries from its current version of 8.1.1?
Also, how do we ensure different maintainers' opinions if they are comfortable with this update on a minor release of wicket-8?

**Comment by martin-g** [comment]
> @martin-g did you check the checksums?

No. I re-downloaded the resources and Git confirmed they are the same.

**Comment by martin-g** [comment]
> From what I understand, there will be a major release of wiquery-core and wiquery-jquery-ui libraries from its current version of 8.1.1?

I've upgraded JQuery UI to 1.13.0 in master branch, i.e. `9.0.0-SNAPSHOT`.


> Also, how do we ensure different maintainers' opinions if they are comfortable with this update on a minor release of wicket-8?

I assume the maintainers who are still interested in WiQuery are still subscribed to the project and read here. If no one raise a concern about doing the same in `wicket-8` branch then I will do it in the coming days!

**Comment by akramshuja** [comment]
@martin-g One last question :). We use gradle to fetch the libraries. Any idea when the new release will be publicly available? The maven repository shows that last update as 8.1.1 3 years ago.

**Comment by martin-g** [comment]
The is one JS problem with the Autocomplete component. Run the demo app and check the browser DevTools Console.
Do you want to help to fix it ?



> last update as 8.1.1 3 years ago

Yes! WiQuery didn't receive much attention since JQueryUI was abondoned several year back.

**Comment by akramshuja** [comment]
@martin-g I'll have a look

**Comment by akramshuja** [comment]
@martin-g Submitted a pull request for the above mentioned issue with autocomplete

**Comment by martin-g** [comment]
@akramshuja Should I proceed with the release ?

**Comment by akramshuja** [comment]
@martin-g Please do. And if other maintainers are OK with it, can we also have this on Wicket 8?

**Comment by martin-g** [comment]
9.0.0 has been released!

**Comment by martin-g** [comment]
And 8.2.0 has been released too!

**Comment by akramshuja** [comment]
Thanks @martin-g . 
Would they be available at this location - https://mvnrepository.com/artifact/org.wicketstuff.wiquery/wiquery-jquery-ui

**Comment by martin-g** [comment]
Probably.
Maven Central is https://repo1.maven.org/maven2/org/wicketstuff/wiquery/wiquery-jquery-ui/.
Everything else is a mirror.

**Pull request merged**
